<?php
// Database connection
$servername = "localhost";
$username = "root"; // Your MySQL username
$password = ""; // Your MySQL password
$dbname = "quiz"; // Your database name

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Handle submitting questions
if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    if (isset($_POST['questions'])) {
        $questions = $_POST['questions']; // Array of questions
        foreach ($questions as $question) {
            $category_id = $question['category'];
            $question_text = $question['question_text'];
            $option_a = $question['option_a'];
            $option_b = $question['option_b'];
            $option_c = $question['option_c'];
            $option_d = $question['option_d'];
            $correct_option = $question['correct_option'];

            // Insert each question into the database
            $sql = "INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_option, category_id) 
                    VALUES ('$question_text', '$option_a', '$option_b', '$option_c', '$option_d', '$correct_option', '$category_id')";

            if (!$conn->query($sql)) {
                $message = "Error: " . $conn->error;
                break;
            }
        }
        $message = "Questions added successfully!";
    }
}

// Close connection
$conn->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submit Questions</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>Submit Questions</h1>
        <?php if (isset($message)) : ?>
            <div class="message"><?php echo $message; ?></div>
        <?php endif; ?>

        <form method="POST" action="submit_question.php">
            <div id="question-form-container">
                <!-- This part will be dynamically generated by JavaScript, as shown earlier -->
                <div class="question-wrapper">
                    <div class="form-group">
                        <label for="category">Select Category:</label>
                        <select name="questions[0][category]" id="category" required>
                            <option value="">Select a category</option>
                            <?php
                            // Fetch categories from the database
                            $sql = "SELECT * FROM categories";
                            $result = $conn->query($sql);
                            while ($row = $result->fetch_assoc()) {
                                echo "<option value='{$row['id']}'>{$row['category_name']}</option>";
                            }
                            ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="question_text0">Question:</label>
                        <textarea name="questions[0][question_text]" id="question_text0" rows="4" required></textarea>
                    </div>

                    <div class="form-group">
                        <label for="option_a0">Option A:</label>
                        <input type="text" name="questions[0][option_a]" id="option_a0" required>
                    </div>

                    <div class="form-group">
                        <label for="option_b0">Option B:</label>
                        <input type="text" name="questions[0][option_b]" id="option_b0" required>
                    </div>

                    <div class="form-group">
                        <label for="option_c0">Option C:</label>
                        <input type="text" name="questions[0][option_c]" id="option_c0" required>
                    </div>

                    <div class="form-group">
                        <label for="option_d0">Option D:</label>
                        <input type="text" name="questions[0][option_d]" id="option_d0" required>
                    </div>

                    <div class="form-group">
                        <label for="correct_option0">Correct Option (A, B, C, D):</label>
                        <input type="text" name="questions[0][correct_option]" id="correct_option0" required>
                    </div>
                </div>
            </div>

            <!-- Buttons -->
            <button type="submit">Submit Questions</button>
        </form>

        <!-- Add another question button -->
        <button type="button" id="add-question-btn">Add Another Question</button>
    </div>

    <script>
        let questionCount = 1;

        // Add another question dynamically
        document.getElementById('add-question-btn').addEventListener('click', function() {
            let questionFormContainer = document.getElementById('question-form-container');
            let newQuestionWrapper = document.createElement('div');
            newQuestionWrapper.classList.add('question-wrapper');

            newQuestionWrapper.innerHTML = `
                <div class="form-group">
                    <label for="category${questionCount}">Select Category:</label>
                    <select name="questions[${questionCount}][category]" required>
                        <option value="">Select a category</option>
                        <?php
                        // Fetch categories from the database
                        $sql = "SELECT * FROM categories";
                        $result = $conn->query($sql);
                        while ($row = $result->fetch_assoc()) {
                            echo "<option value='{$row['id']}'>{$row['category_name']}</option>";
                        }
                        ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="question_text${questionCount}">Question:</label>
                    <textarea name="questions[${questionCount}][question_text]" id="question_text${questionCount}" rows="4" required></textarea>
                </div>

                <div class="form-group">
                    <label for="option_a${questionCount}">Option A:</label>
                    <input type="text" name="questions[${questionCount}][option_a]" required>
                </div>

                <div class="form-group">
                    <label for="option_b${questionCount}">Option B:</label>
                    <input type="text" name="questions[${questionCount}][option_b]" required>
                </div>

                <div class="form-group">
                    <label for="option_c${questionCount}">Option C:</label>
                    <input type="text" name="questions[${questionCount}][option_c]" required>
                </div>

                <div class="form-group">
                    <label for="option_d${questionCount}">Option D:</label>
                    <input type="text" name="questions[${questionCount}][option_d]" required>
                </div>

                <div class="form-group">
                    <label for="correct_option${questionCount}">Correct Option (A, B, C, D):</label>
                    <input type="text" name="questions[${questionCount}][correct_option]" required>
                </div>
            `;
            questionFormContainer.appendChild(newQuestionWrapper);
            questionCount++;
        });
    </script>
</body>
</html>
